data:
  his_size: 20
  npratio: 3
  article_emb_size: 250
  total_train: 172192
  total_test: 215224

info:
  metrics:
  - mrr@3;5;10;20
  - ndcg@3;5;10;20
  - hit@3;5;10;20
  show_step: 100000

model:
  attention_hidden_dim: 128
  rnn_layer_dim: 128
  dense_dim: 128
  model_type: naml
  dense_activation: relu

train:
  batch_size: 8
  epochs: 50
  learning_rate: 0.0001
  loss: cross_entropy_loss
  optimizer: adam
