data:
  article_emb_size: 250
  his_size: 50
  data_format: news
  npratio: 3
  total_train: 172192
  total_test: 215224
  
info:
  metrics:
  - mrr@3;5;10;20
  - ndcg@3;5;10;20
  - hit@3;5;10;20
  show_step: 100000
  
model:
  attention_hidden_dim: 200

  dropout: 0.2
  head_num: 25
  head_dim: 10
  model_type: nrms

train:
  batch_size: 8
  epochs: 50
  learning_rate: 0.0001
  loss: cross_entropy_loss
  optimizer: adam
